services:
  db:
    image: postgres:15
    container_name: clinique-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cleniqueDigitale
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: clinique_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bank.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

  tomcat:
    image: tomee:10.0.0-M3-webprofile
    container_name: clinique_tomcat
    ports:
      - "8081:8080"
      - "8000:8000"
    environment:
      - JPDA_ADDRESS=*:8000
      - JPDA_TRANSPORT=dt_socket
    volumes:
      # Deploy the WAR file. We will handle frontend changes with a separate script.
      - ./target/CliniqueDigitaleJEE.war:/usr/local/tomee/webapps/CliniqueDigitaleJEE.war
    command: catalina.sh jpda run
    depends_on:
      - db

volumes:
  db_data:
